/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTag: typeof import('element-plus/es')['ElTag']
    Icon: typeof import('./src/components/icon/index.vue')['default']
    IconSelector: typeof import('./src/components/icon/IconSelector.vue')['default']
    IonSelector: typeof import('./src/components/icon/IonSelector.vue')['default']
    Mask: typeof import('./src/components/Mask/index.vue')['default']
    Search: typeof import('./src/components/Search/index.vue')['default']
    Svg: typeof import('./src/components/icon/svg/index.vue')['default']
  }
}
