/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseLoading: typeof import('./../src/components/base-loading/base-loading.vue')['default']
    ChaseSpin: typeof import('./../src/components/base-loading/spin/chaseSpin.vue')['default']
    CubeSpin: typeof import('./../src/components/base-loading/spin/cubeSpin.vue')['default']
    DotSpin: typeof import('./../src/components/base-loading/spin/dotSpin.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    Icon: typeof import('./../src/components/icon/index.vue')['default']
    IconSelector: typeof import('./../src/components/icon/IconSelector.vue')['default']
    PlaneSpin: typeof import('./../src/components/base-loading/spin/planeSpin.vue')['default']
    PreloaderSpin: typeof import('./../src/components/base-loading/spin/preloaderSpin.vue')['default']
    PulseSpin: typeof import('./../src/components/base-loading/spin/pulseSpin.vue')['default']
    RectSpin: typeof import('./../src/components/base-loading/spin/rectSpin.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Svg: typeof import('./../src/components/icon/svg/index.vue')['default']
  }
}
